# Generated by Django 5.0.6 on 2024-05-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_remove_order_customer_order_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('edit_order', 'Can edit order')]},
        ),
    ]
