# Generated by Django 5.0.6 on 2024-05-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='order_name',
        ),
    ]
